//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("localization.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alphabetization ähnelt.
        /// </summary>
        public static string Alphabetization {
            get {
                return ResourceManager.GetString("Alphabetization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apprenticeships ähnelt.
        /// </summary>
        public static string Apprenticeships {
            get {
                return ResourceManager.GetString("Apprenticeships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storage used by cache: ähnelt.
        /// </summary>
        public static string CacheSize {
            get {
                return ResourceManager.GetString("CacheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [Calculating...] ähnelt.
        /// </summary>
        public static string Calculating {
            get {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories ähnelt.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose a language ähnelt.
        /// </summary>
        public static string ChooseALanguage {
            get {
                return ResourceManager.GetString("ChooseALanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear cache ähnelt.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact ähnelt.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue ähnelt.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copied to clipboard ähnelt.
        /// </summary>
        public static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crash report ähnelt.
        /// </summary>
        public static string CrashReport {
            get {
                return ResourceManager.GetString("CrashReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disclaimer ähnelt.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured. ähnelt.
        /// </summary>
        public static string ErrorGeneral {
            get {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No active internet connection. ähnelt.
        /// </summary>
        public static string ErrorInternet {
            get {
                return ResourceManager.GetString("ErrorInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured while loading content. ähnelt.
        /// </summary>
        public static string ErrorLoading {
            get {
                return ResourceManager.GetString("ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extras ähnelt.
        /// </summary>
        public static string Extras {
            get {
                return ResourceManager.GetString("Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change for which groups you want to receive notifications for. ähnelt.
        /// </summary>
        public static string FirebaseDescription {
            get {
                return ResourceManager.GetString("FirebaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Push Messages ähnelt.
        /// </summary>
        public static string FirebaseName {
            get {
                return ResourceManager.GetString("FirebaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Has no results. ähnelt.
        /// </summary>
        public static string HasNoResults {
            get {
                return ResourceManager.GetString("HasNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The html raw view is activated ähnelt.
        /// </summary>
        public static string HtmlRawViewActivated {
            get {
                return ResourceManager.GetString("HtmlRawViewActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The html raw view is deactivated ähnelt.
        /// </summary>
        public static string HtmlRawViewDeactivated {
            get {
                return ResourceManager.GetString("HtmlRawViewDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imprint and contact ähnelt.
        /// </summary>
        public static string ImprintAndContact {
            get {
                return ResourceManager.GetString("ImprintAndContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internet connection required. ähnelt.
        /// </summary>
        public static string InternetReq {
            get {
                return ResourceManager.GetString("InternetReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internships ähnelt.
        /// </summary>
        public static string Internships {
            get {
                return ResourceManager.GetString("Internships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jobs ähnelt.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Languages loaded ähnelt.
        /// </summary>
        public static string Languages_loaded {
            get {
                return ResourceManager.GetString("Languages_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location ähnelt.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die News ähnelt.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No recent events available. ähnelt.
        /// </summary>
        public static string NoEvents {
            get {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No extras available. ähnelt.
        /// </summary>
        public static string NoExtras {
            get {
                return ResourceManager.GetString("NoExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No notifications available. ähnelt.
        /// </summary>
        public static string NoPushNotifications {
            get {
                return ResourceManager.GetString("NoPushNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Note: The following extras require an Internet connection. ähnelt.
        /// </summary>
        public static string NoteInternet {
            get {
                return ResourceManager.GetString("NoteInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Push-Notifications ähnelt.
        /// </summary>
        public static string PushNotifications {
            get {
                return ResourceManager.GetString("PushNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Push subscriptions ähnelt.
        /// </summary>
        public static string PushSub {
            get {
                return ResourceManager.GetString("PushSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select when the content may be updated ähnelt.
        /// </summary>
        public static string RefreshOptions {
            get {
                return ResourceManager.GetString("RefreshOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove all data ähnelt.
        /// </summary>
        public static string RemoveAllData {
            get {
                return ResourceManager.GetString("RemoveAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset settings ähnelt.
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The settings have been reseted. ähnelt.
        /// </summary>
        public static string SettingsReseted {
            get {
                return ResourceManager.GetString("SettingsReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select cities which you want to receive push notifications for ähnelt.
        /// </summary>
        public static string SubscribeDescription {
            get {
                return ResourceManager.GetString("SubscribeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Where are you? ähnelt.
        /// </summary>
        public static string WhereAreYou {
            get {
                return ResourceManager.GetString("WhereAreYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Through wifi or mobile data ähnelt.
        /// </summary>
        public static string WifiMobile {
            get {
                return ResourceManager.GetString("WifiMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wifi only ähnelt.
        /// </summary>
        public static string WifiOnly {
            get {
                return ResourceManager.GetString("WifiOnly", resourceCulture);
            }
        }
    }
}
