//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integreat.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Integreat.Localization.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        public static string ChooseALanguage {
            get {
                return ResourceManager.GetString("ChooseALanguage", resourceCulture);
            }
        }
        
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        public static string Extras {
            get {
                return ResourceManager.GetString("Extras", resourceCulture);
            }
        }
        
        public static string ImprintAndContact {
            get {
                return ResourceManager.GetString("ImprintAndContact", resourceCulture);
            }
        }
        
        public static string InternetReq {
            get {
                return ResourceManager.GetString("InternetReq", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        public static string NoEvents {
            get {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }
        
        public static string NoExtras {
            get {
                return ResourceManager.GetString("NoExtras", resourceCulture);
            }
        }
        
        public static string NoPushNotifications {
            get {
                return ResourceManager.GetString("NoPushNotifications", resourceCulture);
            }
        }
        
        public static string NoteInternet {
            get {
                return ResourceManager.GetString("NoteInternet", resourceCulture);
            }
        }
        
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        public static string PushNotifications {
            get {
                return ResourceManager.GetString("PushNotifications", resourceCulture);
            }
        }
        
        public static string RemoveAllData {
            get {
                return ResourceManager.GetString("RemoveAllData", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string WhereAreYou {
            get {
                return ResourceManager.GetString("WhereAreYou", resourceCulture);
            }
        }
        
        public static string Languages_loaded {
            get {
                return ResourceManager.GetString("Languages_loaded", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string HasNoResults {
            get {
                return ResourceManager.GetString("HasNoResults", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        public static string ErrorGeneral {
            get {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }
        
        public static string ErrorInternet {
            get {
                return ResourceManager.GetString("ErrorInternet", resourceCulture);
            }
        }
        
        public static string ErrorLoading {
            get {
                return ResourceManager.GetString("ErrorLoading", resourceCulture);
            }
        }
        
        public static string CrashReport {
            get {
                return ResourceManager.GetString("CrashReport", resourceCulture);
            }
        }
        
        public static string Alphabetization {
            get {
                return ResourceManager.GetString("Alphabetization", resourceCulture);
            }
        }
        
        public static string Apprenticeships {
            get {
                return ResourceManager.GetString("Apprenticeships", resourceCulture);
            }
        }
        
        public static string Internships {
            get {
                return ResourceManager.GetString("Internships", resourceCulture);
            }
        }
        
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        public static string CacheSize {
            get {
                return ResourceManager.GetString("CacheSize", resourceCulture);
            }
        }
        
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        public static string SettingsReseted {
            get {
                return ResourceManager.GetString("SettingsReseted", resourceCulture);
            }
        }
        
        public static string Calculating {
            get {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string HtmlRawViewActivated {
            get {
                return ResourceManager.GetString("HtmlRawViewActivated", resourceCulture);
            }
        }
        
        public static string HtmlRawViewDeactivated {
            get {
                return ResourceManager.GetString("HtmlRawViewDeactivated", resourceCulture);
            }
        }
        
        public static string RefreshOptions {
            get {
                return ResourceManager.GetString("RefreshOptions", resourceCulture);
            }
        }
        
        public static string WifiMobile {
            get {
                return ResourceManager.GetString("WifiMobile", resourceCulture);
            }
        }
        
        public static string WifiOnly {
            get {
                return ResourceManager.GetString("WifiOnly", resourceCulture);
            }
        }
        
        public static string FirebaseDescription {
            get {
                return ResourceManager.GetString("FirebaseDescription", resourceCulture);
            }
        }
        
        public static string FirebaseName {
            get {
                return ResourceManager.GetString("FirebaseName", resourceCulture);
            }
        }
        
        public static string PushSub {
            get {
                return ResourceManager.GetString("PushSub", resourceCulture);
            }
        }
        
        public static string SubscribeDescription {
            get {
                return ResourceManager.GetString("SubscribeDescription", resourceCulture);
            }
        }
        
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        public static string ShareMessage {
            get {
                return ResourceManager.GetString("ShareMessage", resourceCulture);
            }
        }
        
        public static string DisclaimerNotAvailable {
            get {
                return ResourceManager.GetString("DisclaimerNotAvailable", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string ChangeLocation {
            get {
                return ResourceManager.GetString("ChangeLocation", resourceCulture);
            }
        }
        
        public static string DataProtection {
            get {
                return ResourceManager.GetString("DataProtection", resourceCulture);
            }
        }
        
        public static string GetNotificationsFor {
            get {
                return ResourceManager.GetString("GetNotificationsFor", resourceCulture);
            }
        }
        
        public static string EditSubscriptions {
            get {
                return ResourceManager.GetString("EditSubscriptions", resourceCulture);
            }
        }
        
        public static string FCMExplanation {
            get {
                return ResourceManager.GetString("FCMExplanation", resourceCulture);
            }
        }
        
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        public static string FeedbackSent {
            get {
                return ResourceManager.GetString("FeedbackSent", resourceCulture);
            }
        }
        
        public static string WhatIsMissing {
            get {
                return ResourceManager.GetString("WhatIsMissing", resourceCulture);
            }
        }
        
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        public static string ContentFrom {
            get {
                return ResourceManager.GetString("ContentFrom", resourceCulture);
            }
        }
        
        public static string ContentOfThisPage {
            get {
                return ResourceManager.GetString("ContentOfThisPage", resourceCulture);
            }
        }
        
        public static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        public static string TechnicalFunctions {
            get {
                return ResourceManager.GetString("TechnicalFunctions", resourceCulture);
            }
        }
        
        public static string WhatSTheFeedbackFor {
            get {
                return ResourceManager.GetString("WhatSTheFeedbackFor", resourceCulture);
            }
        }
        
        public static string WhatWasHelpful {
            get {
                return ResourceManager.GetString("WhatWasHelpful", resourceCulture);
            }
        }
    }
}
