using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Threading.Tasks;
using Integreat.Localization;
using Integreat.Shared.Data.Loader;
using Integreat.Shared.Models;
using Integreat.Shared.Models.Extras.Raumfrei;
using Integreat.Shared.Services;
using Integreat.Shared.Utilities;
using Integreat.Utilities;
using Xamarin.Forms;

namespace Integreat.Shared.ViewModels
{
    /// <inheritdoc />
    /// <summary>
    /// ViewModel for sprungbrett extra
    /// </summary>
    public class RaumfreiViewModel : BaseContentViewModel
    {
        #region Fields
        private readonly INavigator _navigator;

        private ObservableCollection<RaumfreiOffer> _offers;
        private bool _hasNoResults;
        private readonly Func<RaumfreiOffer, RaumfreiDetailViewModel> _raumfreiDetailPageFactory; // factory generated by AutoFac to resolve a GeneralWebViewPageViewModel instance
        private readonly IParser _parser;

        #endregion

        public RaumfreiViewModel(INavigator navigator,
            DataLoaderProvider dataLoaderProvider,
            Func<RaumfreiOffer, RaumfreiDetailViewModel> raumfreiDetailPageFactory,
            IParser parser)
            : base(dataLoaderProvider)
        {
            Title = "Raumfrei";
            HeaderImage = "sbi_logo";
            _navigator = navigator;
            _raumfreiDetailPageFactory = raumfreiDetailPageFactory;
            _parser = parser;

            Offers = new ObservableCollection<RaumfreiOffer>();

            _navigator.HideToolbar(this);
        }

        #region Properties
        public ObservableCollection<RaumfreiOffer> Offers
        {
            get => _offers;
            private set => SetProperty(ref _offers, value);
        }

        /// <summary>
        /// Gets or sets a value indicating whether this instance has no results for the given location or not.
        /// </summary>
        public bool HasNoResults
        {
            get => _hasNoResults;
            set => SetProperty(ref _hasNoResults, value);
        }

        /// <summary>
        /// Gets the has no results label.
        /// </summary>
        public string HasNoResultsLabel => AppResources.HasNoResults;

        /// <summary>
        /// The displayed header image on the page
        /// </summary>
        public string HeaderImage { get; }

        #endregion

        protected override async void LoadContent(bool forced = false, Language forLanguage = null, Location forLocation = null)
        {
            Offers?.Clear();
            // wait until this resource is free
            await Task.Run(() =>
            {
                while (IsBusy) { /*empty body*/ }
            });
            IsBusy = true;
            HasNoResults = true;


            try
            {
                var offers = await LoadAndGetOffers(Constants.RaumfreiUrl); // ToDo, I guess we have to change this for different possible locations later
                AddTapCommands(offers);
                Offers = offers;
                HasNoResults = false;
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.ToString());
                HasNoResults = true;
            }
            finally { IsBusy = false; }
        }

        private async Task<ObservableCollection<RaumfreiOffer>> LoadAndGetOffers(string url)
        {
            var json = await _parser.FetchAsync<List<RaumfreiOffer>>(url);
            var offers = new ObservableCollection<RaumfreiOffer>(json);
            return offers;
        }

        private void AddTapCommands(IEnumerable<RaumfreiOffer> offers)
        {
            foreach (var offer in offers)
            {
                offer.OnTapCommand = new Command(OnOfferTapped);
                offer.OnSelectCommand = new Command(OnSelectionTapped);
            }
        }

        /// <summary>
        /// Called when an [offer is tapped]. (By a command)
        /// </summary>
        /// <param name="jobOfferObject">The job offer object.</param>
        private async void OnOfferTapped(object offerObject)
        {
            // try to cast the object, abort if failed
            if (!(offerObject is RaumfreiOffer raumfreiOffer)) return;
            var view = _raumfreiDetailPageFactory(raumfreiOffer);
            await _navigator.PushAsync(view, Navigation);
        }

        /// <summary>
        /// Called when an [select button] from an offer is tapped. (By a command)
        /// </summary>
        /// <param name="offerObject">The career offer object.</param>
        private void OnSelectionTapped(object offerObject)
        {
            // try to cast the object, abort if failed
            if (!(offerObject is RaumfreiOffer offer)) return;
            offer.IsSelected = !offer.IsSelected;
            // push a new general webView page, which will show the URL of the offer
        }
    }
}
