#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Integreat.Droid.Test.Resource", IsApplication=true)]

namespace Integreat.Droid.Test
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::Integreat.Droid.Test.Resource.String.library_name;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::Integreat.Droid.Test.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::Integreat.Droid.Test.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::Integreat.Droid.Test.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::Integreat.Droid.Test.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::Integreat.Droid.Test.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::Integreat.Droid.Test.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::Integreat.Droid.Test.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::Integreat.Droid.Test.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::Integreat.Droid.Test.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::Integreat.Droid.Test.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::Integreat.Droid.Test.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::Integreat.Droid.Test.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::Integreat.Droid.Test.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::Integreat.Droid.Test.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::Integreat.Droid.Test.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::Integreat.Droid.Test.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::Integreat.Droid.Test.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::Integreat.Droid.Test.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::Integreat.Droid.Test.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::Integreat.Droid.Test.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::Integreat.Droid.Test.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::Integreat.Droid.Test.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070003
			public const int notification_action_color_filter = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int notification_icon_bg_color = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int notification_material_background_media_default_color = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int primary_text_default_material_dark = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int ripple_material_light = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int secondary_text_default_material_dark = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int secondary_text_default_material_light = 2131165190;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0004
			public const int compat_button_inset_horizontal_material = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int compat_button_inset_vertical_material = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int compat_button_padding_horizontal_material = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int compat_button_padding_vertical_material = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int compat_control_corner_material = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int notification_action_icon_size = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int notification_action_text_size = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int notification_big_circle_margin = 2131361803;
			
			// aapt resource value: 0x7f0a0001
			public const int notification_content_margin_start = 2131361793;
			
			// aapt resource value: 0x7f0a000c
			public const int notification_large_icon_height = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int notification_large_icon_width = 2131361805;
			
			// aapt resource value: 0x7f0a0002
			public const int notification_main_column_padding_top = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int notification_media_narrow_margin = 2131361795;
			
			// aapt resource value: 0x7f0a000e
			public const int notification_right_icon_size = 2131361806;
			
			// aapt resource value: 0x7f0a0000
			public const int notification_right_side_padding_top = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public const int notification_small_icon_background_padding = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int notification_small_icon_size_as_large = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int notification_subtext_size = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int notification_top_pad = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int notification_top_pad_large_text = 2131361811;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_action_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_low_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_normal_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_icon_background = 2130837512;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_template_icon_low_bg = 2130837516;
			
			// aapt resource value: 0x7f020009
			public const int notification_tile_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notify_panel_notification_icon_bg = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050029
			public const int OptionHostName = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int OptionPort = 2131034154;
			
			// aapt resource value: 0x7f050028
			public const int OptionRemoteServer = 2131034152;
			
			// aapt resource value: 0x7f050038
			public const int OptionsButton = 2131034168;
			
			// aapt resource value: 0x7f050033
			public const int ResultFullName = 2131034163;
			
			// aapt resource value: 0x7f050035
			public const int ResultMessage = 2131034165;
			
			// aapt resource value: 0x7f050034
			public const int ResultResultState = 2131034164;
			
			// aapt resource value: 0x7f050032
			public const int ResultRunSingleMethodTest = 2131034162;
			
			// aapt resource value: 0x7f050036
			public const int ResultStackTrace = 2131034166;
			
			// aapt resource value: 0x7f05002e
			public const int ResultsFailed = 2131034158;
			
			// aapt resource value: 0x7f05002b
			public const int ResultsId = 2131034155;
			
			// aapt resource value: 0x7f05002f
			public const int ResultsIgnored = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int ResultsInconclusive = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int ResultsMessage = 2131034161;
			
			// aapt resource value: 0x7f05002d
			public const int ResultsPassed = 2131034157;
			
			// aapt resource value: 0x7f05002c
			public const int ResultsResult = 2131034156;
			
			// aapt resource value: 0x7f050037
			public const int RunTestsButton = 2131034167;
			
			// aapt resource value: 0x7f050039
			public const int TestSuiteListView = 2131034169;
			
			// aapt resource value: 0x7f050017
			public const int action0 = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int action_container = 2131034132;
			
			// aapt resource value: 0x7f05001b
			public const int action_divider = 2131034139;
			
			// aapt resource value: 0x7f050015
			public const int action_image = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int action_text = 2131034134;
			
			// aapt resource value: 0x7f050025
			public const int actions = 2131034149;
			
			// aapt resource value: 0x7f05000f
			public const int async = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int blocking = 2131034128;
			
			// aapt resource value: 0x7f050018
			public const int cancel_action = 2131034136;
			
			// aapt resource value: 0x7f050020
			public const int chronometer = 2131034144;
			
			// aapt resource value: 0x7f050027
			public const int end_padder = 2131034151;
			
			// aapt resource value: 0x7f050011
			public const int forever = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int ghost_view = 2131034112;
			
			// aapt resource value: 0x7f050022
			public const int icon = 2131034146;
			
			// aapt resource value: 0x7f050026
			public const int icon_group = 2131034150;
			
			// aapt resource value: 0x7f050021
			public const int info = 2131034145;
			
			// aapt resource value: 0x7f050012
			public const int italic = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int line1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int line3 = 2131034123;
			
			// aapt resource value: 0x7f05001a
			public const int media_actions = 2131034138;
			
			// aapt resource value: 0x7f050013
			public const int normal = 2131034131;
			
			// aapt resource value: 0x7f050024
			public const int notification_background = 2131034148;
			
			// aapt resource value: 0x7f05001d
			public const int notification_main_column = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int notification_main_column_container = 2131034140;
			
			// aapt resource value: 0x7f050001
			public const int parent_matrix = 2131034113;
			
			// aapt resource value: 0x7f050023
			public const int right_icon = 2131034147;
			
			// aapt resource value: 0x7f05001e
			public const int right_side = 2131034142;
			
			// aapt resource value: 0x7f050002
			public const int save_image_matrix = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int save_non_transition_alpha = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int save_scale_type = 2131034116;
			
			// aapt resource value: 0x7f050019
			public const int status_bar_latest_event_content = 2131034137;
			
			// aapt resource value: 0x7f05000c
			public const int text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int text2 = 2131034125;
			
			// aapt resource value: 0x7f05001f
			public const int time = 2131034143;
			
			// aapt resource value: 0x7f05000e
			public const int title = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int transition_current_scene = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int transition_layout_save = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int transition_position = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int transition_scene_layoutid_cache = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int transition_transform = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int cancel_button_image_alpha = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int status_bar_notification_info_maxnum = 2131230721;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int notification_action = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification_action_tombstone = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_media_action = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_media_cancel_action = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_template_big_media = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_template_big_media_custom = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_big_media_narrow = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_big_media_narrow_custom = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_template_custom_big = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_template_icon_group = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_lines_media = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_media = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_media_custom = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_part_chronometer = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_part_time = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int options = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int results = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int test_result = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int test_suite = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int Hello = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int status_bar_notification_info_overflow = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060005
			public const int TextAppearance_Compat_Notification = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int TextAppearance_Compat_Notification_Info = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int TextAppearance_Compat_Notification_Media = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int TextAppearance_Compat_Notification_Time = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int TextAppearance_Compat_Notification_Title = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int Widget_Compat_NotificationActionContainer = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int Widget_Compat_NotificationActionText = 2131099658;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
